-- MySQL Script generated by MySQL Workbench
-- 04/18/15 21:37:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Restaurante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Restaurante` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Restaurante` ;

-- -----------------------------------------------------
-- Table `Restaurante`.`Proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Proveedores` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Proveedores` (
  `id_proveedor` INT NOT NULL,
  `razon_social` VARCHAR(100) NULL,
  `rfc` VARCHAR(13) NULL,
  `calle` VARCHAR(77) NULL,
  `numero_ext` VARCHAR(6) NULL,
  `numero_int` VARCHAR(10) NULL,
  `colonia` VARCHAR(77) NULL,
  `cp` VARCHAR(7) NULL,
  `ciudad` VARCHAR(77) NULL,
  `estado` VARCHAR(77) NULL,
  `pais` VARCHAR(77) NULL DEFAULT 'México',
  `telefono` VARCHAR(20) NULL,
  `email` VARCHAR(255) NULL,
  `website` VARCHAR(255) NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Clientes` (
  `id_cliente` INT NOT NULL,
  `nombre_razonsocial` VARCHAR(100) NULL,
  `rfc` VARCHAR(13) NULL,
  `calle` VARCHAR(77) NULL,
  `numero_ext` VARCHAR(6) NULL,
  `numero_int` VARCHAR(10) NULL,
  `colonia` VARCHAR(77) NULL,
  `cp` VARCHAR(7) NULL,
  `ciudad` VARCHAR(77) NULL,
  `estado` VARCHAR(77) NULL,
  `pais` VARCHAR(77) NULL DEFAULT 'México',
  `telefono` VARCHAR(20) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Ingredientes` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Ingredientes` (
  `id_ingrediente` INT NOT NULL,
  `nombre` VARCHAR(77) NULL,
  `precio` FLOAT NULL,
  `descripcion` VARCHAR(255) NULL,
  `unidad_medida` VARCHAR(77) NULL,
  `stock` INT NULL,
  PRIMARY KEY (`id_ingrediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Recetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Recetas` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Recetas` (
  `id_receta` INT NOT NULL,
  `nombre` VARCHAR(77) NULL,
  `descripcion` VARCHAR(255) NULL,
  `precio` FLOAT NULL,
  `algoritmo` TEXT NULL,
  `porciones` INT NULL,
  `notas` VARCHAR(255) NULL,
  PRIMARY KEY (`id_receta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Platillos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Platillos` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Platillos` (
  `id_platillo` INT NOT NULL,
  `nombre` VARCHAR(77) NULL,
  `descripcion` VARCHAR(255) NULL,
  `precio` FLOAT NULL,
  `Recetas_id_receta` INT NOT NULL,
  PRIMARY KEY (`id_platillo`, `Recetas_id_receta`),
  INDEX `fk_Platillos_Recetas1_idx` (`Recetas_id_receta` ASC),
  CONSTRAINT `fk_Platillos_Recetas1`
    FOREIGN KEY (`Recetas_id_receta`)
    REFERENCES `Restaurante`.`Recetas` (`id_receta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Bebidas_Preparadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Bebidas_Preparadas` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Bebidas_Preparadas` (
  `id_bebida_preparada` INT NOT NULL,
  `id_receta` INT NULL,
  `id_receta` INT NOT NULL,
  PRIMARY KEY (`id_bebida_preparada`, `id_receta`),
  INDEX `fk_Bebidas_Preparadas_Recetas1_idx` (`id_receta` ASC),
  CONSTRAINT `fk_Bebidas_Preparadas_Recetas1`
    FOREIGN KEY (`id_receta`)
    REFERENCES `Restaurante`.`Recetas` (`id_receta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Bebidas_Comerciales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Bebidas_Comerciales` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Bebidas_Comerciales` (
  `id_bebida_comercial` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(255) NULL,
  `copeada` TINYINT(1) NULL,
  `precio` DECIMAL(10,0) NULL,
  PRIMARY KEY (`id_bebida_comercial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Bebidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Bebidas` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Bebidas` (
  `id_bebida` INT NOT NULL,
  `tipo_bebida` VARCHAR(45) NULL,
  `nombre` VARCHAR(128) NULL,
  `descripcion` VARCHAR(255) NULL,
  `precio` DECIMAL(10,0) NULL,
  `id_bebida_preparada` INT NOT NULL,
  `id_bebida_comercial` INT NOT NULL,
  PRIMARY KEY (`id_bebida`, `id_bebida_preparada`, `id_bebida_comercial`),
  INDEX `fk_Bebidas_Bebidas_Preparadas_idx` (`id_bebida_preparada` ASC),
  INDEX `fk_Bebidas_Bebidas_Comerciales1_idx` (`id_bebida_comercial` ASC),
  CONSTRAINT `fk_Bebidas_Bebidas_Preparadas`
    FOREIGN KEY (`id_bebida_preparada`)
    REFERENCES `Restaurante`.`Bebidas_Preparadas` (`id_bebida_preparada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bebidas_Bebidas_Comerciales1`
    FOREIGN KEY (`id_bebida_comercial`)
    REFERENCES `Restaurante`.`Bebidas_Comerciales` (`id_bebida_comercial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Compras` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Compras` (
  `id_Compra` INT NOT NULL,
  `produto` VARCHAR(100) NULL,
  `descripcion` VARCHAR(255) NULL,
  `precio` FLOAT NULL,
  `stock` INT NULL,
  `notas` VARCHAR(255) NULL,
  PRIMARY KEY (`id_Compra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Insumos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Insumos` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Insumos` (
  `id_Insumo` INT NOT NULL,
  `nombre` VARCHAR(77) NULL,
  `descripcion` VARCHAR(255) NULL,
  `precio` FLOAT NULL,
  `stock` INT NULL,
  PRIMARY KEY (`id_Insumo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Mesas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Mesas` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Mesas` (
  `id_mesa` INT NOT NULL,
  `num_mesa` INT NULL,
  `area` VARCHAR(45) NULL,
  `capacidad_comensales` INT NULL DEFAULT 4,
  PRIMARY KEY (`id_mesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Personal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Personal` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Personal` (
  `id_personal` INT NOT NULL,
  `nombre` VARCHAR(77) NULL,
  `apellidos` VARCHAR(77) NULL,
  `rfc` VARCHAR(13) NULL,
  `calle` VARCHAR(77) NULL,
  `numero_ext` VARCHAR(6) NULL,
  `numero_int` VARCHAR(10) NULL,
  `colonia` VARCHAR(77) NULL,
  `cp` VARCHAR(7) NULL DEFAULT '49340',
  `ciudad` VARCHAR(77) NULL DEFAULT 'Tapalpa',
  `estado` VARCHAR(77) NULL DEFAULT 'Jalisco',
  `pais` VARCHAR(77) NULL DEFAULT 'México',
  `telefono_fijo` VARCHAR(20) NULL,
  `movil` VARCHAR(20) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id_personal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Comandas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Comandas` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Comandas` (
  `id_comanda` INT NOT NULL,
  `Clientes_id_cliente` INT NOT NULL,
  `Mesas_id_mesa` INT NOT NULL,
  `Platillos_id_platillo` INT NOT NULL,
  `Platillos_Recetas_id_receta` INT NOT NULL,
  `Bebidas_id_bebida` INT NOT NULL,
  `Bebidas_id_bebida_preparada` INT NOT NULL,
  `Bebidas_id_bebida_comercial` INT NOT NULL,
  `Personal_id_personal` INT NOT NULL,
  `notas` VARCHAR(255) NULL,
  `total` FLOAT NULL,
  PRIMARY KEY (`id_comanda`, `Clientes_id_cliente`, `Mesas_id_mesa`, `Platillos_id_platillo`, `Platillos_Recetas_id_receta`, `Bebidas_id_bebida`, `Bebidas_id_bebida_preparada`, `Bebidas_id_bebida_comercial`, `Personal_id_personal`),
  INDEX `fk_Comandas_Mesas1_idx` (`Mesas_id_mesa` ASC),
  INDEX `fk_Comandas_Platillos1_idx` (`Platillos_id_platillo` ASC, `Platillos_Recetas_id_receta` ASC),
  INDEX `fk_Comandas_Bebidas1_idx` (`Bebidas_id_bebida` ASC, `Bebidas_id_bebida_preparada` ASC, `Bebidas_id_bebida_comercial` ASC),
  INDEX `fk_Comandas_Personal1_idx` (`Personal_id_personal` ASC),
  CONSTRAINT `fk_Comandas_Mesas1`
    FOREIGN KEY (`Mesas_id_mesa`)
    REFERENCES `Restaurante`.`Mesas` (`id_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comandas_Platillos1`
    FOREIGN KEY (`Platillos_id_platillo` , `Platillos_Recetas_id_receta`)
    REFERENCES `Restaurante`.`Platillos` (`id_platillo` , `Recetas_id_receta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comandas_Bebidas1`
    FOREIGN KEY (`Bebidas_id_bebida` , `Bebidas_id_bebida_preparada` , `Bebidas_id_bebida_comercial`)
    REFERENCES `Restaurante`.`Bebidas` (`id_bebida` , `id_bebida_preparada` , `id_bebida_comercial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comandas_Personal1`
    FOREIGN KEY (`Personal_id_personal`)
    REFERENCES `Restaurante`.`Personal` (`id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Reservaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Reservaciones` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Reservaciones` (
  `id_reservacion` INT NOT NULL,
  `fecha` DATETIME NULL,
  `notas` VARCHAR(255) NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_reservacion`, `id_cliente`),
  INDEX `fk_Reservaciones_Clientes1_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_Reservaciones_Clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `Restaurante`.`Clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Reservaciones_Mesas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Reservaciones_Mesas` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Reservaciones_Mesas` (
  `id_reservacion` INT NOT NULL,
  `id_mesa` INT NOT NULL,
  PRIMARY KEY (`id_reservacion`, `id_mesa`),
  INDEX `fk_Reservaciones_has_Mesas_Mesas1_idx` (`id_mesa` ASC),
  INDEX `fk_Reservaciones_has_Mesas_Reservaciones1_idx` (`id_reservacion` ASC),
  CONSTRAINT `fk_Reservaciones_has_Mesas_Reservaciones1`
    FOREIGN KEY (`id_reservacion`)
    REFERENCES `Restaurante`.`Reservaciones` (`id_reservacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservaciones_has_Mesas_Mesas1`
    FOREIGN KEY (`id_mesa`)
    REFERENCES `Restaurante`.`Mesas` (`id_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Proveedores_Insumos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Proveedores_Insumos` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Proveedores_Insumos` (
  `id_proveedor` INT NOT NULL,
  `id_Insumo` INT NOT NULL,
  PRIMARY KEY (`id_proveedor`, `id_Insumo`),
  INDEX `fk_Proveedores_has_Insumos_Insumos1_idx` (`id_Insumo` ASC),
  INDEX `fk_Proveedores_has_Insumos_Proveedores1_idx` (`id_proveedor` ASC),
  CONSTRAINT `fk_Proveedores_has_Insumos_Proveedores1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `Restaurante`.`Proveedores` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proveedores_has_Insumos_Insumos1`
    FOREIGN KEY (`id_Insumo`)
    REFERENCES `Restaurante`.`Insumos` (`id_Insumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Proveedores_Compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Proveedores_Compras` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Proveedores_Compras` (
  `id_proveedor` INT NOT NULL,
  `id_Compra` INT NOT NULL,
  PRIMARY KEY (`id_proveedor`, `id_Compra`),
  INDEX `fk_Proveedores_has_Compras_Compras1_idx` (`id_Compra` ASC),
  INDEX `fk_Proveedores_has_Compras_Proveedores1_idx` (`id_proveedor` ASC),
  CONSTRAINT `fk_Proveedores_has_Compras_Proveedores1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `Restaurante`.`Proveedores` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proveedores_has_Compras_Compras1`
    FOREIGN KEY (`id_Compra`)
    REFERENCES `Restaurante`.`Compras` (`id_Compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Ingredientes_Recetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Ingredientes_Recetas` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Ingredientes_Recetas` (
  `id_ingrediente` INT NOT NULL,
  `id_receta` INT NOT NULL,
  PRIMARY KEY (`id_ingrediente`, `id_receta`),
  INDEX `fk_Ingredientes_has_Recetas_Recetas1_idx` (`id_receta` ASC),
  INDEX `fk_Ingredientes_has_Recetas_Ingredientes1_idx` (`id_ingrediente` ASC),
  CONSTRAINT `fk_Ingredientes_has_Recetas_Ingredientes1`
    FOREIGN KEY (`id_ingrediente`)
    REFERENCES `Restaurante`.`Ingredientes` (`id_ingrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingredientes_has_Recetas_Recetas1`
    FOREIGN KEY (`id_receta`)
    REFERENCES `Restaurante`.`Recetas` (`id_receta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Clientes_has_Comandas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Clientes_has_Comandas` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Clientes_has_Comandas` (
  `Clientes_id_cliente` INT NOT NULL,
  `Comandas_id_comanda` INT NOT NULL,
  `Comandas_Clientes_id_cliente` INT NOT NULL,
  `Comandas_Mesas_id_mesa` INT NOT NULL,
  `Comandas_Platillos_id_platillo` INT NOT NULL,
  `Comandas_Platillos_Recetas_id_receta` INT NOT NULL,
  `Comandas_Bebidas_id_bebida` INT NOT NULL,
  `Comandas_Bebidas_id_bebida_preparada` INT NOT NULL,
  `Comandas_Bebidas_id_bebida_comercial` INT NOT NULL,
  `Comandas_Personal_id_personal` INT NOT NULL,
  PRIMARY KEY (`Clientes_id_cliente`, `Comandas_id_comanda`, `Comandas_Clientes_id_cliente`, `Comandas_Mesas_id_mesa`, `Comandas_Platillos_id_platillo`, `Comandas_Platillos_Recetas_id_receta`, `Comandas_Bebidas_id_bebida`, `Comandas_Bebidas_id_bebida_preparada`, `Comandas_Bebidas_id_bebida_comercial`, `Comandas_Personal_id_personal`),
  INDEX `fk_Clientes_has_Comandas_Comandas1_idx` (`Comandas_id_comanda` ASC, `Comandas_Clientes_id_cliente` ASC, `Comandas_Mesas_id_mesa` ASC, `Comandas_Platillos_id_platillo` ASC, `Comandas_Platillos_Recetas_id_receta` ASC, `Comandas_Bebidas_id_bebida` ASC, `Comandas_Bebidas_id_bebida_preparada` ASC, `Comandas_Bebidas_id_bebida_comercial` ASC, `Comandas_Personal_id_personal` ASC),
  INDEX `fk_Clientes_has_Comandas_Clientes1_idx` (`Clientes_id_cliente` ASC),
  CONSTRAINT `fk_Clientes_has_Comandas_Clientes1`
    FOREIGN KEY (`Clientes_id_cliente`)
    REFERENCES `Restaurante`.`Clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_has_Comandas_Comandas1`
    FOREIGN KEY (`Comandas_id_comanda` , `Comandas_Clientes_id_cliente` , `Comandas_Mesas_id_mesa` , `Comandas_Platillos_id_platillo` , `Comandas_Platillos_Recetas_id_receta` , `Comandas_Bebidas_id_bebida` , `Comandas_Bebidas_id_bebida_preparada` , `Comandas_Bebidas_id_bebida_comercial` , `Comandas_Personal_id_personal`)
    REFERENCES `Restaurante`.`Comandas` (`id_comanda` , `Clientes_id_cliente` , `Mesas_id_mesa` , `Platillos_id_platillo` , `Platillos_Recetas_id_receta` , `Bebidas_id_bebida` , `Bebidas_id_bebida_preparada` , `Bebidas_id_bebida_comercial` , `Personal_id_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurante`.`Proveedores_Ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurante`.`Proveedores_Ingredientes` ;

CREATE TABLE IF NOT EXISTS `Restaurante`.`Proveedores_Ingredientes` (
  `id_proveedor` INT NOT NULL,
  `id_ingrediente` INT NOT NULL,
  PRIMARY KEY (`id_proveedor`, `id_ingrediente`),
  INDEX `fk_Proveedores_has_Ingredientes_Ingredientes1_idx` (`id_ingrediente` ASC),
  INDEX `fk_Proveedores_has_Ingredientes_Proveedores1_idx` (`id_proveedor` ASC),
  CONSTRAINT `fk_Proveedores_has_Ingredientes_Proveedores1`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `Restaurante`.`Proveedores` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proveedores_has_Ingredientes_Ingredientes1`
    FOREIGN KEY (`id_ingrediente`)
    REFERENCES `Restaurante`.`Ingredientes` (`id_ingrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
